services:
  - type: web
    name: todolist-spring-boot
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/todolist-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /api/tarefas
    autoDeploy: true
